# Generated by Django 4.2.3 on 2024-04-08 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entrega",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nmClnt", models.CharField(max_length=255)),
                ("endrNtrg", models.TextField()),
                ("dtEntrega", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Frutas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nmeFrt", models.CharField(max_length=100)),
                ("prcFrt", models.DecimalField(decimal_places=2, max_digits=6)),
                ("qntdDspnvl", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Pagamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mtPgto", models.CharField(max_length=50)),
                ("vlrTotal", models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name="Verduras",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nmVdx", models.CharField(max_length=100)),
                ("pXcVdX", models.DecimalField(decimal_places=2, max_digits=6)),
                ("stkVxL", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nmItm", models.CharField(max_length=100)),
                ("qntdd", models.IntegerField()),
                ("prcUnit", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "entrega",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="app.entrega",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="entrega",
            name="pagamento",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entrega",
                to="app.pagamento",
            ),
        ),
    ]
