# Generated by Django 4.2.3 on 2024-04-19 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_dtentrega_entrega_datadeentrega_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagamento',
            old_name='FormasDePagamento',
            new_name='mtPgto',
        ),
        migrations.RenameField(
            model_name='pagamento',
            old_name='valorTotal',
            new_name='vlrTotal',
        ),
    ]
